# Copyright (c) 2023 - 2025 Chair for Design Automation, TUM
# Copyright (c) 2025 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

name: 📝 • CodeQL • Python
on:
  workflow_call:

jobs:
  analyze:
    name: 🐍 Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      # check out the repository (including submodules and all history)
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: recursive
          fetch-depth: 0
      # initialize CodeQL with the extended security-and-quality queries
      - name: Initialize CodeQL
        uses: github/codeql-action/init@ce28f5bb42b7a9f2c824e633a3f6ee835bab6858 # v3
        with:
          languages: python
          config: |
            queries:
            - uses: security-and-quality
      # perform the CodeQL analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@ce28f5bb42b7a9f2c824e633a3f6ee835bab6858 # v3
