# Copyright (c) 2023 - 2026 Chair for Design Automation, TUM
# Copyright (c) 2025 - 2026 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

name: 🐍 • Packaging

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-python-packaging-wheel
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-wheel:
    name: 🛞 Wheel
    runs-on: ubuntu-latest
    env:
      IQM_TOKEN: ${{ secrets.IQM_TOKEN }}
      IQM_QC_ALIAS: ${{ secrets.IQM_QC_ALIAS }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      # check out the repository (including submodules and all history)
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false
      # set up uv for faster Python package management
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          save-cache: ${{ github.ref == 'refs/heads/main' }}
      # build the wheel
      - name: Build Wheel
        run: uv build --wheel
      # check the metadata of the wheel
      - name: Check metadata
        run: uvx twine check dist/*
      # upload the wheel as an artifact (adds a `dev-` prefix for PRs)
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ github.event_name == 'pull_request' && 'dev-' || '' }}cibw-wheel
          path: dist/*.whl
