# Copyright (c) 2023 - 2025 Chair for Design Automation, TUM
# Copyright (c) 2025 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

name: 🐍 • Packaging

on:
  workflow_call:
    inputs:
      runs-on:
        description: "The runner image to test on"
        default: "ubuntu-24.04"
        type: string
      setup-z3:
        description: "Whether to set up Z3"
        default: false
        type: boolean
      z3-version:
        description: "The version of Z3 to set up"
        default: "4.13.4"
        type: string
      setup-mlir:
        description: "Whether to set up MLIR"
        default: false
        type: boolean
      llvm-version:
        description: "The LLVM version to set up (formatted as 'major.minor.patch') or commit hash (minimum 7 characters, e.g., 'a832a52')"
        default: "21.1.8"
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-python-packaging-cibw-${{ inputs.runs-on }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-wheel:
    name: 🎡 ${{ inputs.runs-on }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Z3
        if: ${{ inputs.setup-z3 && !startsWith(inputs.runs-on, 'ubuntu') }}
        uses: cda-tum/setup-z3@8156b32632230f11cf9c5a50becb33d73e2fb4e5 # v1.7.1
        with:
          version: ${{ inputs.z3-version }}

      - name: Set up MLIR
        if: ${{ inputs.setup-mlir && !startsWith(inputs.runs-on, 'ubuntu') }}
        uses: munich-quantum-software/setup-mlir@81729fff6f2b938a65a059b7401cb9b0144afcaa # v1.0.1
        with:
          llvm-version: ${{ inputs.llvm-version }}

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
        with:
          enable-cache: ${{ !startsWith(inputs.runs-on, 'ubuntu') }}
          save-cache: ${{ github.ref == 'refs/heads/main' }}

      # set up sccache for faster builds (non-Ubuntu only)
      - name: Install sccache
        if: ${{ !startsWith(inputs.runs-on, 'ubuntu') }}
        run: uv tool install sccache

      # run cibuildwheel to build wheels for the specified Python version
      - uses: pypa/cibuildwheel@298ed2fb2c105540f5ed055e8a6ad78d82dd3a7e # v3.3.1

      - name: Verify clean directory
        run: git diff --exit-code
        shell: bash

      # upload the wheels as an artifact (adds a `dev-` prefix for PRs)
      - name: Upload wheels
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ github.event_name == 'pull_request' && 'dev-' || '' }}cibw-wheels-${{ inputs.runs-on }}
          path: wheelhouse/*.whl

      - name: Show sccache stats
        if: ${{ !startsWith(inputs.runs-on, 'ubuntu') }}
        run: sccache --show-stats
