# Copyright (c) 2023 - 2025 Chair for Design Automation, TUM
# Copyright (c) 2025 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

name: 🇨 • Tests • macos
on:
  workflow_call:
    inputs:
      runs-on:
        description: >
          The macOS runner image to use. Defaults to 'macos-latest'.
          This can be any valid macOS runner image, such as 'macos-13', 'macos-14', or 'macos-15'.
        default: "macos-latest"
        type: string
      config:
        description: >
          The build type to use. Defaults to 'Release'.
          This can be any valid CMake build type, such as 'Debug' or 'Release'.
        default: "Release"
        type: string
      compiler:
        description: >
          The compiler to use. Defaults to 'clang'.
          This can be 'clang' or 'gcc'.
          If 'clang' is selected, this will use the default Apple Clang compiler.
          If 'gcc-XX' is selected, this will use `gcc-XX` from Homebrew, where XX is the version number (e.g., 'gcc-14').
          A specific version of Clang, including MLIR, can be requested via 'clang-XX', where XX is the version number (e.g., 'clang-20').
        default: "clang"
        type: string
      cmake-args:
        description: >
          Additional arguments to pass to CMake. Defaults to an empty string.
          This can be any valid CMake argument, such as '-DBUILD_SHARED_LIBS=ON'.
        default: ""
        type: string
      setup-z3:
        description: "Whether to set up Z3"
        default: false
        type: boolean
      z3-version:
        description: "The version of Z3 to set up"
        default: "4.13.4"
        type: string

jobs:
  cpp-tests-macos:
    name: 🍎 ${{ inputs.runs-on }} ${{ inputs.compiler }} ${{ inputs.config }}
    runs-on: ${{ inputs.runs-on }}
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      CTEST_PARALLEL_LEVEL: 4
      FORCE_COLOR: 3
    steps:
      # check out the repository (including submodules and all history)
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: recursive
          fetch-depth: 0
      # optionally set up Z3
      - if: ${{ inputs.setup-z3 }}
        name: Setup Z3
        uses: cda-tum/setup-z3@4bc179e7fc1cd1a7f5f13429246c692041b19eb3 # v1
        with:
          version: ${{ inputs.z3-version }}
      # set up ccache for faster C++ builds
      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@563420fe2f8f1dd18ad6e58deeb3abfc1b28819e # v1
        with:
          prepend_symlinks_to_path: false
          override_cache_key: c++-tests-${{ inputs.runs-on }}-${{ inputs.config }}-${{ inputs.compiler }}
      # make sure ninja is installed
      - name: Install Ninja
        run: brew install ninja
      # set up gcc if specified
      - if: ${{ startsWith(inputs.compiler, 'gcc-') }}
        name: Set up GCC
        env:
          COMPILER: ${{ inputs.compiler }}
        run: |
          if [[ "$COMPILER" =~ ^gcc-[0-9]+$ ]]; then
            version=$(echo "$COMPILER" | sed 's/gcc-//')
            brew install gcc@$version
            echo "CC=gcc-$version" >> $GITHUB_ENV
            echo "CXX=g++-$version" >> $GITHUB_ENV
          else
            echo "Invalid compiler specified: $COMPILER" >&2
            exit 1
          fi
      # set up clang if specified
      - if: ${{ startsWith(inputs.compiler, 'clang-') }}
        name: Set up Clang
        env:
          COMPILER: ${{ inputs.compiler }}
        run: |
          if [[ "$COMPILER" =~ ^clang-[0-9]+$ ]]; then
            version=$(echo "$COMPILER" | sed 's/clang-//')
            brew install llvm@$
      # configure CMake in the specified mode, optionally with additional arguments
      - name: Configure CMake
        env:
          CONFIG: ${{ inputs.config }}
          CMAKE_ARGS: ${{ inputs.cmake-args }}
        run: cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE="$CONFIG" "$CMAKE_ARGS"
      # build the project in the specified mode
      - name: Build
        env:
          CONFIG: ${{ inputs.config }}
        run: cmake --build build --config "$CONFIG"
      # run the tests
      - name: Test
        env:
          CONFIG: ${{ inputs.config }}
        run: ctest -C "$CONFIG" --output-on-failure --test-dir build --repeat until-pass:3 --timeout 600
