# Copyright (c) 2023 - 2026 Chair for Design Automation, TUM
# Copyright (c) 2025 - 2026 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

name: 🇨 • Coverage
on:
  workflow_call:
    inputs:
      cmake-args:
        description: "Additional arguments to pass to CMake"
        default: "-G Ninja"
        type: string
      setup-z3:
        description: "Whether to set up Z3"
        default: false
        type: boolean
      z3-version:
        description: "The version of Z3 to set up"
        default: "4.13.4"
        type: string
      setup-mlir:
        description: "Whether to set up MLIR"
        default: false
        type: boolean
      llvm-version:
        description: "The LLVM version to set up (formatted as 'major.minor.patch') or commit hash (minimum 7 characters, e.g., 'a832a52')"
        default: "21.1.8"
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-cpp-coverage
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  coverage:
    name: 📈 Coverage
    runs-on: ubuntu-24.04
    permissions:
      contents: read # Required for the `actions/checkout` action
      id-token: write # Required for the `codecov/codecov-action` action
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      CTEST_PARALLEL_LEVEL: 4
      FORCE_COLOR: 3
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Z3
        if: ${{ inputs.setup-z3 }}
        uses: cda-tum/setup-z3@7bfe87519f27304460db44284cb8cc59f50f5fc9 # v1.7.2
        with:
          version: ${{ inputs.z3-version }}

      - name: Set up MLIR
        if: ${{ inputs.setup-mlir }}
        uses: munich-quantum-software/setup-mlir@f3ebc0bd966545a052741bc2b31750c34a09aa22 # v1.3.0
        with:
          llvm-version: ${{ inputs.llvm-version }}

      # set up ccache for faster builds
      - name: Set up ccache
        uses: Chocobo1/setup-ccache-action@f433cb1e0b3ed576864d7fc361ce43b23b181e67 # v1.5.4
        with:
          prepend_symlinks_to_path: false
          override_cache_key: c++-coverage

      - name: Set up mold as linker
        uses: rui314/setup-mold@725a8794d15fc7563f59595bd9556495c0564878 # v1

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          python-version: 3.13
          activate-environment: true
          enable-cache: false

      - name: Install Ninja
        run: uv tool install ninja

      - name: Install lit
        if: ${{ inputs.setup-mlir }}
        run: uv pip install lit

      - name: Configure CMake
        env:
          CMAKE_ARGS: ${{ inputs.cmake-args }}
          SETUP_MLIR: ${{ inputs.setup-mlir }}
        run: |
          LIT_ARG=""
          if [ "$SETUP_MLIR" = "true" ]; then
            LIT_ARG="-DLLVM_EXTERNAL_LIT=$(which lit)"
          fi
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON $CMAKE_ARGS "$LIT_ARG"

      - name: Build
        run: cmake --build build --config Debug

      - name: Test
        run: ctest -C Debug --output-on-failure --test-dir build --repeat until-pass:3 --timeout 600

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          fail_ci_if_error: true
          flags: cpp
          use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
