# Copyright (c) 2023 - 2025 Chair for Design Automation, TUM
# Copyright (c) 2025 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

name: 🐍 • Packaging

on:
  workflow_call:

jobs:
  build-sdist:
    name: 📦 SDist
    runs-on: ubuntu-latest
    steps:
      # check out the repository (including submodules and all history)
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          submodules: recursive
          fetch-depth: 0
      # set up uv for faster Python package management
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3 # v7.1.3
        with:
          enable-cache: true
          save-cache: ${{ github.ref == 'refs/heads/main' }}
      # build the source distribution
      - name: Build SDist
        run: uv build --sdist
      # check the metadata of the source distribution
      - name: Check metadata
        run: uvx twine check dist/*
      # upload the source distribution as an artifact (adds a `dev-` prefix for PRs)
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: ${{ github.event_name == 'pull_request' && 'dev-' || '' }}cibw-sdist
          path: dist/*.tar.gz
