# Copyright (c) 2023 - 2025 Chair for Design Automation, TUM
# Copyright (c) 2025 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

name: 🐍 • Lint
on:
  workflow_call:
    inputs:
      enable-ty:
        description: "Whether to enable Astral's ty for type checking"
        default: false
        type: boolean
      enable-mypy:
        description: "Whether to enable mypy for type checking"
        default: true
        type: boolean
      setup-z3:
        description: "Whether to set up Z3"
        default: false
        type: boolean
      z3-version:
        description: "The version of Z3 to set up"
        default: "4.13.4"
        type: string
      setup-mlir:
        description: "Whether to set up MLIR"
        default: false
        type: boolean
      llvm-version:
        description: "The version of LLVM to set up (formatted as 'major.minor.patch')"
        default: "21.1.7"
        type: string

jobs:
  lint:
    name: 🚨 Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Z3
        if: ${{ inputs.setup-z3 }}
        uses: cda-tum/setup-z3@edb99468071192a5a4e2c4dbdb15f74a9df11d09 # v1.7.0
        with:
          version: ${{ inputs.z3-version }}

      - name: Set up MLIR
        if: ${{ inputs.setup-mlir }}
        uses: munich-quantum-software/setup-mlir@6b8d4ef561ca19268764609adf9fa12f53015e1f # 2025.12.05
        with:
          llvm-version: ${{ inputs.llvm-version }}

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
        with:
          enable-cache: true
          save-cache: ${{ github.ref == 'refs/heads/main' }}

      # run mypy for static type checking
      - name: Run mypy
        if: ${{ inputs.enable-mypy }}
        run: uvx prek run -a mypy

      # run ty for type checking
      - name: Run ty
        if: ${{ inputs.enable-ty }}
        run: |
          uv sync --no-install-project
          uv run --no-sync ty check

      # run check-sdist to ensure the package sdist is correct
      - name: Run check-sdist
        run: uvx check-sdist --inject-junk
