# Copyright (c) 2023 - 2025 Chair for Design Automation, TUM
# Copyright (c) 2025 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

name: 🐍 • Packaging

on:
  workflow_call:

jobs:
  build-wheel:
    name: 🛞 Wheel
    runs-on: ubuntu-latest
    steps:
      # check out the repository (including submodules and all history)
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: recursive
          fetch-depth: 0
      # set up uv for faster Python package management
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba # v6
      # build the wheel
      - name: Build Wheel
        run: uv build --wheel
      # check the metadata of the wheel
      - name: Check metadata
        run: uvx twine check dist/*
      # upload the wheel as an artifact (adds a `dev-` prefix for PRs)
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ github.event_name == 'pull_request' && 'dev-' || '' }}cibw-wheel
          path: dist/*.whl
