# Copyright (c) 2023 - 2025 Chair for Design Automation, TUM
# Copyright (c) 2025 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

name: 📝 • CodeQL • C++
on:
  workflow_call:
    inputs:
      cmake-args:
        description: "Additional arguments to pass to CMake"
        default: ""
        type: string
      setup-z3:
        description: "Whether to set up Z3"
        default: false
        type: boolean
      z3-version:
        description: "The version of Z3 to set up"
        default: "4.13.4"
        type: string

jobs:
  analyze:
    name: 🇨 Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
    steps:
      # check out the repository (including submodules and all history)
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: recursive
          fetch-depth: 0
      # optionally set up Z3
      - if: ${{ inputs.setup-z3 }}
        name: Setup Z3
        uses: cda-tum/setup-z3@34d1e04d31a168fa330626fad1275cf23de02591 # v1
        with:
          version: ${{ inputs.z3-version }}
      # set up ccache for faster C++ builds
      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@563420fe2f8f1dd18ad6e58deeb3abfc1b28819e # v1
        with:
          prepend_symlinks_to_path: false
          override_cache_key: codeql-cpp
      # set up mold as linker for faster C++ builds
      - name: Set up mold as linker
        uses: rui314/setup-mold@b3958095189f34b95d402a680b6e96b7f194f7b9 # v1
      # initialize CodeQL with the extended security-and-quality queries
      - name: Initialize CodeQL
        uses: github/codeql-action/init@fca7ace96b7d713c7035871441bd52efbe39e27e # v3
        with:
          languages: cpp
          config: |
            queries:
              - uses: security-and-quality
      # configure CMake in Debug mode, optionally with additional arguments
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug ${{ inputs.cmake-args }}
      # build the project
      - name: Build
        run: cmake --build build
      # run CodeQL analysis without uploading results (to avoid false positives on third party code)
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@fca7ace96b7d713c7035871441bd52efbe39e27e # v3
        with:
          upload: False
          output: sarif-results
      # filter out third party code from the results
      - name: filter-sarif
        uses: advanced-security/filter-sarif@main
        with:
          patterns: |
            -**/extern/**
            -**/build/**
          input: sarif-results/cpp.sarif
          output: sarif-results/cpp.sarif
      # upload the results to CodeQL
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@fca7ace96b7d713c7035871441bd52efbe39e27e # v3
        with:
          sarif_file: sarif-results/cpp.sarif
