# Copyright (c) 2023 - 2025 Chair for Design Automation, TUM
# Copyright (c) 2025 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

name: 🐍 • CI

on:
  workflow_call:
    inputs:
      runs-on:
        description: "The runner image to test on"
        default: "ubuntu-24.04"
        type: string
      setup-z3:
        description: "Whether to set up Z3"
        default: false
        type: boolean
      z3-version:
        description: "The version of Z3 to set up"
        default: "4.13.4"
        type: string

jobs:
  python-tests:
    name: 🐍 ${{ inputs.runs-on }}
    uses: ./.github/workflows/reusable-python-tests.yml
    with:
      runs-on: ${{ inputs.runs-on }}
      setup-z3: ${{ inputs.setup-z3 }}
      z3-version: ${{ inputs.z3-version }}

  python-coverage-upload:
    name: 📈
    needs: [python-tests]
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for the `actions/checkout` action
      id-token: write # Required for the `codecov/codecov-action` action
    steps:
      # check out the repository (mostly for the codecov config)
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      # download coverage reports from all jobs
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          pattern: coverage-*
          path: coverage-reports
          merge-multiple: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5
        with:
          fail_ci_if_error: true
          flags: python
          use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
