# Copyright (c) 2023 - 2025 Chair for Design Automation, TUM
# Copyright (c) 2025 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

name: 🐍 • Tests
on:
  workflow_call:
    inputs:
      runs-on:
        description: "The platform to run the tests on"
        required: true
        type: string
      setup-z3:
        description: "Whether to set up Z3"
        default: false
        type: boolean
      z3-version:
        description: "The version of Z3 to set up"
        default: "4.13.4"
        type: string

jobs:
  python-tests:
    name: 🐍 ${{ inputs.runs-on }}
    runs-on: ${{ inputs.runs-on }}
    env:
      FORCE_COLOR: 3
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      # check out the repository (including submodules and all history)
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: recursive
          fetch-depth: 0
      # optionally set up Z3
      - if: ${{ inputs.setup-z3 }}
        name: Setup Z3
        uses: cda-tum/setup-z3@b1aecd324aca7d6056d3ec203194779ac785949d # v1.6.7
        with:
          version: ${{ inputs.z3-version }}
      # set up mold as linker for faster C++ builds (Linux only)
      - name: Set up mold as linker (Linux only)
        uses: rui314/setup-mold@725a8794d15fc7563f59595bd9556495c0564878 # v1
      # set up uv for faster Python package management
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@2ddd2b9cb38ad8efd50337e8ab201519a34c9f24 # v7.1.1
        with:
          enable-cache: true
          save-cache: ${{ github.ref == 'refs/heads/main' }}
      # set up sccache for faster C++ builds
      - name: Install sccache
        run: uv tool install sccache
      # run the nox minimums session (assumes a nox session named "minimums" exists) with coverage
      - name: 🐍 Test with minimal versions
        run: uvx nox -s minimums --verbose -- --cov --cov-report=xml:coverage-${{ inputs.runs-on }}.xml --cov-append
      # run the nox tests session (assumes a nox session named "tests" exists) with coverage
      - name: 🐍 Test
        run: uvx nox -s tests --verbose -- --cov --cov-report=xml:coverage-${{ inputs.runs-on }}.xml --cov-append
      # upload the report as an artifact to GitHub so that it can later be uploaded to Codecov
      - name: Upload 🐍 coverage report for ${{ inputs.runs-on }}
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: coverage-${{ inputs.runs-on }}
          path: coverage-*
      # show sccache stats
      - name: Show sccache stats
        run: sccache --show-stats
