# Copyright (c) 2023 - 2026 Chair for Design Automation, TUM
# Copyright (c) 2025 - 2026 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

name: 🐍 • Packaging

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-python-packaging-sdist
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-sdist:
    name: 📦 SDist
    runs-on: ubuntu-slim
    steps:
      # check out the repository (including submodules and all history)
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false
      # set up uv for faster Python package management
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0
        with:
          enable-cache: true
          save-cache: ${{ github.ref == 'refs/heads/main' }}
      # build the source distribution
      - name: Build SDist
        run: uv build --sdist
      # check the metadata of the source distribution
      - name: Check metadata
        run: uvx twine check dist/*
      # upload the source distribution as an artifact (adds a `dev-` prefix for PRs)
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ github.event_name == 'pull_request' && 'dev-' || '' }}cibw-sdist
          path: dist/*.tar.gz
