# Copyright (c) 2023 - 2025 Chair for Design Automation, TUM
# Copyright (c) 2025 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

name: Templating
on:
  pull_request:
    paths:
      - ".github/workflows/templating.yml"
  workflow_dispatch: # Allow manual triggering

jobs:
  render-template:
    name: Render template
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: create-token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: munich-quantum-toolkit/templates@c51416e95539e22a22b36736eacb3ba9cd533220
        with:
          token: ${{ steps.create-token.outputs.token }}
          name: Reusable Workflows
          organization: ${{ github.repository_owner }}
          project-type: other
          repository: ${{ github.event.repository.name }}
          synchronize-contribution-guide: false
          synchronize-documentation-utilities: false
          synchronize-installation-guide: false
