# Copyright (c) 2023 - 2026 Chair for Design Automation, TUM
# Copyright (c) 2025 - 2026 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

name: Templating
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/templating.yml"
  workflow_dispatch: # Allow manual triggering

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  render-template:
    name: Render template
    runs-on: ubuntu-slim
    environment: mqt-app
    permissions:
      contents: write # Needed to push changes to the repository
      pull-requests: write # Needed to create a PR
    steps:
      - id: create-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write
      - uses: munich-quantum-toolkit/templates@73ca06a4fa58d37cf4520de21228f0008a0b6d90 # v1.4.0
        with:
          token: ${{ steps.create-token.outputs.token }}
          name: Reusable Workflows
          organization: ${{ github.repository_owner }}
          project-type: other
          repository: ${{ github.event.repository.name }}
          synchronize-contribution-guide: false
          synchronize-documentation-utilities: false
          synchronize-installation-guide: false
